#
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (Server) - https://serverproject.com
# See the file 'doc/COPYING' for copying permission
#
server:
    module:
        invisible_iframe:
            enable: true
            category: "Misc"
            name: "Create Invisible Iframe"
            description: "Creates an invisible iframe."
            authors: ["bcoles"]
            target:
                working: ["ALL"]
