#
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (Server) - https://serverproject.com
# See the file 'doc/COPYING' for copying permission
#
server:
    module:
        detect_foxit:
            enable: false
            category: "Browser"
            name: "Detect Foxit Reader"
            description: "This module will check if the browser has Foxit Reader Plugin."
            authors: ["javuto"]
            target:
                working: ["All"]
