#
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (Server) - https://serverproject.com
# See the file 'doc/COPYING' for copying permission
#
server:
    extension:
        proxy:
            name: 'Proxy'
            enable: false
            address: "127.0.0.1"
            port: 6789
            authors: ["antisnatchor", "scotty"]
            key: "server_key.pem"
            cert: "server_cert.pem"
