#
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (Server) - https://serverproject.com
# See the file 'doc/COPYING' for copying permission
#
server:
    module:
        detect_realplayer:
            enable: false
            category: "Browser"
            name: "Detect RealPlayer"
            description: "This module will check if the browser has RealPlayer support."
            authors: ["gcattani"]
            target:
                working: ["All"]
