#
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (Server) - https://serverproject.com
# See the file 'doc/COPYING' for copying permission
#
#   phonegap persistence
#
server:
    module:
        phonegap_persistence:
            enable: true
            category: "Phonegap"
            name: "Persistence (PhoneGap)"
            description: "Insert the Server hook into PhoneGap's index.html (iPhone only). This module requires the PhoneGap API."
            authors: ["mh"]
            target:
                working: ["All"]
