#
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (Server) - https://serverproject.com
# See the file 'doc/COPYING' for copying permission
#
server:
    module:
        Detect_toolbars:
            enable: false
            category: "Browser"
            name: "Detect Toolbars"
            description: "Detects which browser toolbars are installed."
            authors: ["gcattani"]
            target:
                working: ["All"]
