#
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (Server) - https://serverproject.com
# See the file 'doc/COPYING' for copying permission
#
server:
    extension:
        requester:
            name: 'Requester'
            enable: false
            authors: ["antisnatchor", "scotty"]
