# Generated by Django 5.2.11 on 2026-02-10 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('raw_data', models.TextField()),
                ('parsed_data', models.JSONField(default=dict)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 score based on risk analysis')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['hostname', 'timestamp'], name='telemetry_t_hostnam_9f8759_idx'), models.Index(fields=['risk_score'], name='telemetry_t_risk_sc_12c210_idx')],
            },
        ),
    ]
