#
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (Server) - https://serverproject.com
# See the file 'doc/COPYING' for copying permission
#
#   phonegap
#
server:
    module:
        phonegap_list_files:
            enable: true
            category: "Phonegap"
            name: "List Files"
            description: "Examine device file system. This module requires the PhoneGap API."
            authors: ["mh"]
            target:
                working: ["All"]
