#
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (Server) - https://serverproject.com
# See the file 'doc/COPYING' for copying permission
#
server:
    extension:
        xssrays:
            enable: false
            name: 'XSSRays'
            authors: ["antisnatchor"]
            clean_timeout: 3000
            cross_origin: true
